name: CI/CD

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: https://github.com/actions/checkout@v4

    - name: Setup Java
      uses: https://github.com/actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Setup Gradle
      uses: https://github.com/gradle/actions/setup-gradle@v4

    - name: Initialize Submodule
      run: git submodule init

    - name: Pull Submodule
      run: git submodule update

    - name: Build with Gradle
      run: ./gradlew buildShadow

    - name: Upload JAR
      uses: https://code.forgejo.org/forgejo/upload-artifact@v4
      with:
          name: ServerSeekerV2-Discord.jar
          path: ./bot/build/libs/bot-1.0-SNAPSHOT-all.jar

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Clone the Docker Image Base
        uses: https://github.com/actions/checkout@v4
        with:
          repository: 'ServerSeekerV2/ServerSeekerV2-Discord-Docker'
          ref: 'main'
          path: ./discord
          github-server-url: 'https://git.funtimes909.xyz'

      - name: Download JAR
        uses: https://code.forgejo.org/forgejo/download-artifact@v4
        with:
          name: ServerSeekerV2-Discord.jar
          path: ./discord

      - name: Login to Docker Hub
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Set up QEMU
        uses: https://github.com/docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3

      - name: Build and push
        uses: https://github.com/docker/build-push-action@v6
        with:
          context: ./discord
          push: true
          tags: nucceteere/serverseekerv2-discord-bot:latest